Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,1 +1,57 @@
+name: Check CloudFormation Templates with CFN Guard
 
+on: [push]
+
+jobs:
+  fuzz:
+    strategy:
+      matrix:
+        target: ["guard_dsl", "yaml"]
+    runs-on: ubuntu-latest
+    name: Run Fuzz Checks
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions-rust-lang/setup-rust-toolchain@v1
+        with:
+          toolchain: nightly
+          matcher: false
+          rustflags: ""
+      - uses: actions-rs/cargo@v1
+        name: Install cargo-fuzz
+        with:
+          command: install
+          args: cargo-fuzz
+      - name: fuzz ${{ matrix.target }}
+        run: |
+          cd guard/fuzz
+          cargo +nightly fuzz run fuzz_${{ matrix.target }} -- -max_total_time=${{ env.FUZZ_TIME }}
+
+  aws-guard-rules-registry-integration-tests-linux-and-macos:
+    strategy:
+      matrix:
+        os: [ubuntu-latest, macos-latest, macos-13-xlarge]
+    runs-on: ${{ matrix.os }}
+    name: Integration tests against aws-guard-rules-registry
+    steps:
+      - uses: actions/checkout@v3
+        name: Checkout cfn-guard
+        with:
+          path: cloudformation-guard
+      - name: Build binary
+        run: |
+          cd cloudformation-guard/guard/
+          cargo build --release
+      - uses: actions/checkout@v3
+        name: Checkout aws-guard-rules-registry
+        with:
+          repository: aws-cloudformation/aws-guard-rules-registry
+          path: aws-guard-rules-registry
+          ref: main
+      - name: Run integration tests using test command
+        run: |
+          if cloudformation-guard/target/release/cfn-guard test -d aws-guard-rules-registry/rules; then
+              echo "The integration tests for test command have passed."
+          else
+              echo "The integration tests for test command have failed."
+              exit 1
+          fi
